---
apiVersion: "extensions/v1beta1"
kind: DaemonSet
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    tier: node
    component: kube-proxy
spec:
  template:
    metadata:
      labels:
        tier: node
        component: kube-proxy
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: kube-proxy
        image: gcr.io/google_containers/hyperkube-amd64:v1.6.2
        command:
        - /hyperkube
        - proxy
        - --cluster-cidr=10.2.0.0/16
        - --hostname-override=$(NODE_NAME)
        - --kubeconfig=/etc/kubernetes/auth/admin.conf
        - --proxy-mode=iptables
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: auth
          mountPath: /etc/kubernetes/auth
#        - name: pki
#          mountPath: /etc/kubernetes/pki
      hostNetwork: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: auth
        hostPath:
          path: /etc/kubernetes/auth
#      - name: pki
#        hostPath:
#          path: /etc/kubernetes/pki
