{{- $tenant := .Values.tenant -}}
{{- $cluster := .Values.cluster -}}
{{- $service_name := .Values.etcd.service_name -}}
{{- $service := (print $service_name "-discovery." .Release.Namespace ".svc.cluster.local") -}}
{{- $replicas := .Values.etcd.replicas -}}

---
apiVersion: "extensions/v1beta1"
kind: DaemonSet
metadata:
  name: {{ $service_name }}
  labels:
    tenant: {{ $tenant }}
    cluster: {{ $cluster }}
    tier: pump-control-plane
    component: k8s-etcd
spec:
  template:
    metadata:
      labels:
        tenant: {{ $tenant }}
        cluster: {{ $cluster }}
        tier: pump-control-plane
        component: k8s-etcd
    spec:
      nodeSelector:
        cp-tenant-{{ $tenant }}: "true"
        cp-cluster-{{ $cluster }}: "true"
      containers:
        - name: etcd
          image: {{ .Values.etcd.image }}
          imagePullPolicy: {{ .Values.etcd.image_pull_policy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ETCD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: http://{{ .Values.etcd.service_name }}:2379
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: http://$(POD_IP):2380
            - name: ETCD_DATA_DIR
              value: /var/oilrig/pump/etcd/k8s
            - name: ETCD_DISCOVERY_SRV
              value: {{ .Values.etcd.service_name }}-discovery
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: "{{ $tenant }}-{{ $cluster }}-k8s-etcd"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: http://0.0.0.0:2379
            - name: ETCD_LISTEN_PEER_URLS
              value: http://0.0.0.0:2380
          ports:
            - name: client
              containerPort: 2379
            - name: peer
              containerPort: 2380
          volumeMounts:
            - name: data
              mountPath: /var/oilrig/pump/etcd/k8s
      volumes:
        - name: data
          hostPath:
            path: /var/oilrig/pump/{{ $tenant }}/{{ $cluster }}/etcd/k8s
