{{- $tenant := .Values.tenant -}}
{{- $cluster := .Values.cluster -}}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-apiserver
  labels:
    tenant-{{ $tenant }}: control-plane
    cluster-{{ $cluster }}: control-plane
    tier: pump-control-plane
    component: k8s-apiserver
spec:
  replicas: {{ .Values.apiserver.replicas }}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        tenant-{{ $tenant }}: control-plane
        cluster-{{ $cluster }}: control-plane
        tier: pump-control-plane
        component: k8s-apiserver
    spec:
      nodeSelector:
        tenant-{{ $tenant }}: control-plane
        cluster-{{ $cluster }}: control-plane
      containers:
        - name: kube-apiserver
          image: gcr.io/google_containers/hyperkube-amd64:v1.6.2
          command:
            - /hyperkube
            - apiserver
            - --apiserver-count=3
#            - --advertise-address=$(POD_IP)
            - --v=3
            - --authorization-mode=RBAC,AlwaysAllow
            - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds
            - --anonymous-auth=false
            - --insecure-port=0
            - --bind-address=0.0.0.0
            - --secure-port=443
            - --allow-privileged=true
            - --etcd-servers=http://k8s-etcd:2379
            - --service-cluster-ip-range={{ .Values.network.service_cidr }}

#            - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
            - --service-account-key-file=/etc/kubernetes/pki/keys/pub/sa.pub
            - --client-ca-file=/etc/kubernetes/pki/certs/ca.crt
            - --tls-cert-file=/etc/kubernetes/pki/certs/apiserver.crt
            - --tls-private-key-file=/etc/kubernetes/pki/keys/priv/apiserver.key
            - --requestheader-client-ca-file=/etc/kubernetes/pki/certs/ca.crt
          volumeMounts:
            - name: pki-certs
              mountPath: /etc/kubernetes/pki/certs
            - name: pki-apiserver
              mountPath: /etc/kubernetes/pki/keys/priv
            - name: pki-sa-pub
              mountPath: /etc/kubernetes/pki/keys/pub
      volumes:
        - name: pki-certs
          configMap:
            name: k8s-certs
        - name: pki-sa-pub
          configMap:
            name: k8s-sa-pub
        - name: pki-apiserver
          secret:
            secretName: k8s-key-apiserver
