{{- $tenant := .Values.tenant -}}
{{- $cluster := .Values.cluster -}}

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-np
  labels:
    tenant: {{ $tenant }}
    cluster: {{ $cluster }}
    tier: pump-control-plane
    component: k8s-apiserver
spec:
  selector:
    tenant: {{ $tenant }}
    cluster: {{ $cluster }}
    tier: pump-control-plane
    component: k8s-apiserver
  type: NodePort
  ports:
    - name: https
      port: 443
      nodePort: 30443
    - name: http
      port: 80
      nodePort: 30080
