{{- $tenant := .Values.tenant -}}
{{- $cluster := .Values.cluster -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.etcd.service_name }}
  labels:
    tenant: {{ $tenant }}
    cluster: {{ $cluster }}
    tier: pump-control-plane
    component: k8s-etcd
spec:
  selector:
    tenant: {{ $tenant }}
    cluster: {{ $cluster }}
    tier: pump-control-plane
    component: k8s-etcd
  ports:
    - name: etcd-client
      port: 2379
    - name: etcd-server
      port: 2380
