version: '2'

services:
   etcd:
     command: etcd --listen-client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://0.0.0.0:2379 --data-dir=/var/lib/etcd
     image: gcr.io/google_containers/etcd-amd64:3.0.17
     volumes:
      - /var/lib/etcd:/var/lib/etcd:rw
     restart: always
     dns: 8.8.8.8
   kube_apiserver:
     links:
      - etcd:etcd
     command: kube-apiserver --etcd-servers=http://etcd:2379 --service-cluster-ip-range=10.96.0.0/12 -v=99 --insecure-bind-address 0.0.0.0 --insecure-port 8080
     image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.2
     restart: always
     dns: 8.8.8.8
   kube_controller_manager:
     links:
      - kube_apiserver:kube-apiserver
     command: kube-controller-manager --master http://kube-apiserver:8080 --address 127.0.0.1 -v=99
     image: gcr.io/google_containers/kube-controller-manager-amd64:v1.6.2
     restart: always
     dns: 8.8.8.8
   kube_scheduler:
     links:
      - kube_apiserver:kube-apiserver
     command: kube-scheduler --master http://kube-apiserver:8080 -v-99
     image: gcr.io/google_containers/kube-scheduler-amd64:v1.6.2
     restart: always
     dns: 8.8.8.8
