---
apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    tier: control-plane
    component: kube-scheduler
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  hostNetwork: true
  containers:
    - name: kube-scheduler
      image: gcr.io/google_containers/hyperkube-amd64:v1.6.2
      command:
      - ./hyperkube
      - scheduler
      - --leader-elect=true
      - --kubeconfig=/etc/kubernetes/auth/admin.conf
      - --port=20251
      - --v=2
      volumeMounts:
        - name: auth
          mountPath: /etc/kubernetes/auth
#        - name: pki
#          mountPath: /etc/kubernetes/pki
  volumes:
    - name: auth
      hostPath:
        path: /etc/kubernetes/auth
#    - name: pki
#      hostPath:
#        path: /etc/kubernetes/pki
