---
apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    tier: control-plane
    component: kube-controller-manager
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  hostNetwork: true
  dnsPolicy: Default # Don't use cluster DNS.
  containers:
    - name: kube-controller-manager
      image: gcr.io/google_containers/hyperkube-amd64:v1.6.2
      command:
      - ./hyperkube
      - controller-manager
      - --allocate-node-cidrs=true
      - --cluster-cidr=10.2.0.0/16
      - --configure-cloud-routes=false
      - --leader-elect=true
      - --kubeconfig=/etc/kubernetes/auth/admin.conf
      - --port=20252
#      - --root-ca-file=/etc/kubernetes/pki/ca.crt
      - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
#      - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
#      - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
      - --use-service-account-credentials=true
      - --v=2
      volumeMounts:
        - name: auth
          mountPath: /etc/kubernetes/auth
        - name: pki
          mountPath: /etc/kubernetes/pki
  volumes:
    - name: auth
      hostPath:
        path: /etc/kubernetes/auth
    - name: pki
      hostPath:
        path: /etc/kubernetes/pki
