---
apiVersion: v1
kind: Pod
metadata:
  name: kube-asset-registerer
  namespace: oilrig
spec:
  # Host network is required, since we cannot rely on CNI being available, yet.
  hostNetwork: true
  initContainers:
    - name: register-assets
      image: gcr.io/google_containers/hyperkube-amd64:v1.6.2
      command:
        - /hyperkube
        - kubectl
        - --kubeconfig
        - /etc/kubernetes/auth/admin.conf
        - apply
        - -f
        - /etc/kubernetes/dynamic-manifests
      volumeMounts:
        - name: auth
          mountPath: /etc/kubernetes/auth
        - name: manifests
          mountPath: /etc/kubernetes/dynamic-manifests
        - name: pki
          mountPath: /etc/kubernetes/pki
  containers:
    - name: done
      image: gcr.io/google_containers/pause-amd64:3.0
  volumes:
    - name: auth
      hostPath:
        path: /etc/kubernetes/auth
    - name: manifests
      hostPath:
        path: /etc/kubernetes/dynamic-manifests
    - name: pki
      hostPath:
        path: /etc/kubernetes/pki
